/* Live transport and persistent background jobs. No credentials leave the Python process. */
let runtime=null,modelList=[],pollTimer=null,job=null,clientBusy=false,accountError='',evidenceMessage=null;
const prefsKey=()=> 'dynasty.settings.'+(selected||'default');
function readPrefs(){try{return JSON.parse(localStorage.getItem(prefsKey())||'{}')}catch{return {}}}
const post=async(path,body,retry=true)=>{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':runtime.csrf},body:JSON.stringify(body)});const data=await r.json().catch(()=>({error:'Unexpected response (HTTP '+r.status+'). Refresh the page'}));if(r.status===403&&data.code==='stale_token'&&retry){runtime={...runtime,csrf:(await get('/api/config')).csrf};return post(path,body,false)}if(!r.ok)throw Error(data.error||'Request failed. Refresh the page');return data};
async function refreshAccounts(){runtime=await get('/api/config');const old=$('#liveAccount').value;$('#liveAccount').innerHTML=runtime.accounts.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('')||'<option value="">Not signed in</option>';$('#liveAccount').value=runtime.accounts.some(x=>x.id===old)?old:(runtime.active||runtime.accounts[0]?.id||'');$('#liveSnapshot').innerHTML=(runtime.snapshots.length?`<option value="latest">Latest save · ${esc(runtime.snapshots[0].game_date)}</option>`:'')+runtime.snapshots.map(x=>`<option value="${x.id}">${esc(x.game_date)} · Snapshot ${x.id}</option>`).join('');if(runtime.login?.status==='waiting'){$('#loginLink').hidden=false;$('#loginLink').href=runtime.login.url}$('#accountStatus').textContent=runtime.login?.message||''}
async function refreshModels(){accountError='';if(!$('#liveAccount').value){modelList=[];$('#liveModel').innerHTML='<option value="">Sign in first</option>';updateSend();return}$('#accountStatus').textContent='Loading available models…';try{modelList=await post('/api/models',{account:$('#liveAccount').value});const preference=readPrefs().model||chats.find(c=>c.id===selected)?.model||'gpt-5.6-sol';$('#liveModel').innerHTML=modelList.map(x=>`<option value="${esc(x.slug)}">${esc(x.label)}</option>`).join('');$('#liveModel').value=modelList.some(x=>x.slug===preference)?preference:modelList[0]?.slug||'';$('#accountStatus').textContent=`Loaded  ${modelList.length}  available models`}catch(e){accountError=e.message;$('#accountStatus').textContent=e.message;modelList=[];$('#liveModel').innerHTML='<option value="">Loading failed; refresh</option>'}updateSend()}
function updateSend(){const running=job?.state==='running';$('#send').disabled=clientBusy||running||!$('#liveModel').value;$('#send').textContent=running?'Generating…':clientBusy?'Submitting…':'Send ↑';$('.model-chip').textContent='◈ '+($('#liveModel').selectedOptions[0]?.textContent||'Sign in under Settings');$('.lookup').textContent=$('#liveLookup').checked?'✓ On-demand evidence':'Story writing';$('#retryLive').disabled=running||clientBusy||!$('#liveModel').value}
/* "latest" follows new imports; a dated option pins the conversation to that save. */
window.refreshSnapshots=async()=>{const keep=$('#liveSnapshot').value;await refreshAccounts();$('#liveSnapshot').value=[...$('#liveSnapshot').options].some(o=>o.value===keep)?keep:'latest';await loadPeople();await syncOverview()};
function snapshotId(){const v=$('#liveSnapshot').value;return v==='latest'?runtime.snapshots[0]?.id:Number(v)}
async function loadPeople(){const saved=readPrefs().people||[];const p=await get('/api/people?snapshot='+snapshotId());$('#livePeople').innerHTML=p.map(x=>`<option value="${esc(x.id)}" ${saved.includes(x.id)?'selected':''}>${esc(x.name)}</option>`).join('')}
function currentConfig(){return {language:window.uiLanguage||'en',account:$('#liveAccount').value,model:$('#liveModel').value,snapshot_id:snapshotId(),follow_latest:$('#liveSnapshot').value==='latest',season:$('#liveSeason').value.trim(),kind:$('#liveKind').value,scope:$('#liveScope').value,people:[...$('#livePeople').selectedOptions].map(x=>x.value),require_lookup:$('#liveLookup').checked}}
async function applyPrefs(){if(!runtime)return;const p=readPrefs();$('#liveSnapshot').value=p.follow_latest===false&&runtime.snapshots.some(x=>x.id===p.snapshot_id)?String(p.snapshot_id):'latest';$('#liveSeason').value=p.season||overview.season||'';$('#liveKind').value=p.kind||'overall';$('#liveScope').value=p.scope||'first_team';$('#liveLookup').checked=p.require_lookup??true;const preferred=p.model||chats.find(c=>c.id===selected)?.model||'gpt-5.6-sol';if(modelList.some(x=>x.slug===preferred))$('#liveModel').value=preferred;await loadPeople();await syncOverview();updateSend()}
const originalLoadChat=loadChat;
loadChat=async function(id){if(clientBusy){toast('Saving your question; please wait');return}clearTimeout(pollTimer);job=null;await originalLoadChat(id);await liveReady;if(selected!==id)return;await applyPrefs();await pollJob(id)};
const originalEvidence=openEvidence;
openEvidence=async function(id,label){evidenceMessage=id;await originalEvidence(id,label)};
async function pollJob(room){if(selected!==room)return;try{const result=await get('/api/jobs?chat='+encodeURIComponent(room));if(selected!==room)return;const previous=job;job=result[0]||null;const running=job?.state==='running';$('#jobStatus').hidden=!running;$('#retryLive').hidden=running||!messages.length||!(messages.at(-1).role==='user'||messages.at(-1).status==='incomplete');if(running){const e=await get('/api/evidence?message='+encodeURIComponent(job.assistant_id));if(selected!==room)return;const last=e.workflow.at(-1);$('#jobStatus').innerHTML='<span class="spinner"></span><div><b>Analyzing in the background</b><small>'+esc(last?.title||'Request queued')+' · '+esc(last?.elapsed_seconds??0)+'s · Refreshing or switching conversations will not interrupt this job</small></div><button id="liveEvidence" class="outline">View execution ↗</button>';$('#liveEvidence').onclick=()=>openEvidence(job.assistant_id,'Current background job');if(!$('#evidence').hidden&&evidenceMessage===job.assistant_id){evidence=e;renderEvidence()}}if(previous?.state==='running'&&!running){messages=await get('/api/messages?chat='+encodeURIComponent(room));if(selected!==room)return;renderConversation();toast(job?.state==='complete'?'Answer saved':'This response is incomplete. Expand it for details');$('#retryLive').hidden=job?.state==='complete';}updateSend();pollTimer=setTimeout(()=>pollJob(room),running?1800:7000)}catch(e){$('#jobStatus').hidden=false;$('#jobStatus').textContent='Connection temporarily interrupted; the job is not automatically resubmitted. '+e.message;pollTimer=setTimeout(()=>pollJob(room),5000)}}
async function refreshChatList(){chats=await get('/api/chats');renderChats()}
async function createRoom(){const title=prompt(tr(mode==='analysis'?'New analysis conversation title':'New dressing-room conversation title'));if(title===null)return;try{await liveReady;const r=await post('/api/create',{title,mode});await refreshChatList();await loadChat(r.id);$('#draft').focus()}catch(e){toast(e.message)}}
$('#newChat').onclick=createRoom;
async function realSend(retry=false){
 if(clientBusy||job?.state==='running')return;
 await liveReady;
 const room=selected;
 if(!room){toast('Create a conversation first');return}
 const question=$('#draft').value.trim();if(!retry&&!question)return;
 clientBusy=true;updateSend();
 const cfg=currentConfig();localStorage.setItem(prefsKey(),JSON.stringify(cfg));
 const key='dynasty.pending.'+room;let pending;
 try{pending=JSON.parse(sessionStorage.getItem(key)||'null')}catch{}
 const signature=JSON.stringify({question,retry,...cfg});
 if(!pending||pending.signature!==signature){pending={id:crypto.randomUUID(),signature};sessionStorage.setItem(key,JSON.stringify(pending))}
 try{
  const submitted=await post('/api/send',{...cfg,question,retry,chat_id:room,request_id:pending.id});
  sessionStorage.removeItem(key);
  if(selected===room){job=submitted;if(!retry)$('#draft').value='';const saved=await get('/api/messages?chat='+encodeURIComponent(room));if(selected===room){messages=saved;renderConversation();clearTimeout(pollTimer);await pollJob(room)}}
  await refreshChatList();
 }catch(e){toast(e.message);if(selected===room){$('#jobStatus').hidden=false;$('#jobStatus').textContent=e.message+' Your input is preserved.'}}
 finally{clientBusy=false;updateSend()}
}
send=()=>realSend(false);$('#send').onclick=send;$('#retryLive').onclick=()=>realSend(true);
$('#refreshLive').onclick=async()=>{try{await refreshAccounts();await refreshModels();await applyPrefs()}catch(e){toast(e.message)}};$('#liveAccount').onchange=refreshModels;$('#liveModel').onchange=updateSend;$('#liveLookup').onchange=updateSend;$('#liveSnapshot').onchange=loadPeople;
$('#loginLive').onclick=async()=>{try{const result=await post('/api/login',{account:$('#liveAccount').value});$('#loginLink').href=result.url;$('#loginLink').hidden=false;$('#accountStatus').textContent='Follow the link below to authorize, then refresh account  /  models.'}catch(e){toast(e.message)}};
$('#logoutLive').onclick=async()=>{try{await post('/api/logout',{account:$('#liveAccount').value});await refreshAccounts();await refreshModels()}catch(e){toast(e.message)}};
$('#saveSettings').onclick=async()=>{localStorage.setItem(prefsKey(),JSON.stringify(currentConfig()));document.body.classList.toggle('compact',$('#density').value==='compact');$('#settingsDialog').close();await syncOverview();updateSend();toast('Settings saved for the next message')};
const liveReady=(async()=>{try{await refreshAccounts();await refreshModels();await applyPrefs();if(!modelList.length)toast('Open workspace settings to sign in or refresh models')}catch(e){accountError=e.message;$('#accountStatus').textContent=e.message;toast(e.message)}})();
/* Headcanon remains an explicit action, never an automatic model side effect. */
const originalRender=renderConversation;
renderConversation=function(){originalRender();document.querySelectorAll('.turn-toggle').forEach(b=>b.addEventListener('click',()=>{if(mode!=='story')return;const answer=b.closest('.turn').querySelector('.answer');answer.querySelectorAll('[data-evidence]').forEach(eb=>{if(eb.parentNode.querySelector('.collect-button'))return;const m=messages.find(x=>x.id===eb.dataset.evidence);if(m?.status!=='complete')return;const collect=document.createElement('button');collect.className='collect-button';collect.textContent='Collect headcanon';collect.onclick=async()=>{const title=prompt(tr('Story title'));if(!title)return;try{await post('/api/collect',{...currentConfig(),message_id:m.id,title});toast('Saved to the story archive')}catch(e){toast(e.message)}};eb.parentNode.append(collect)})}))};

async function syncOverview(){const day=runtime.snapshots.find(x=>x.id===snapshotId())?.game_date;if(!day)return;overview=await get('/api/overview?date='+encodeURIComponent(day));renderOverview();$('#snapshot').textContent='Data through · '+(overview.game_date||'Not imported');}
